### ISSUE TITLE
Fails to compile on FreeBSD 11.0

### ISSUE THREAD

**Issue by ghost** [thestinger/vte-ng#19]
```
gmake[1]: Entering directory '/usr/home/gregf/vte-ng/glade'
gmake[1]: Leaving directory '/usr/home/gregf/vte-ng/glade'
gmake  all-recursive
gmake[1]: Entering directory '/usr/home/gregf/vte-ng'
Making all in src
gmake[2]: Entering directory '/usr/home/gregf/vte-ng/src'
  GEN      box_drawing.h
  GEN      marshal.cc
  GEN      marshal.h
  GEN      vtetypebuiltins.cc
  GEN      stamp-vtetypebuiltins.h
  GEN      vteresources.cc
  GEN      vteseq-n.cc
git.mk: Generating .gitignore
gmake  all-am
gmake[3]: Entering directory '/usr/home/gregf/vte-ng/src'
  CXX      libvte_2_91_la-caps.lo
In file included from caps.cc:20:0:
/usr/local/lib/gcc5/gcc/x86_64-portbld-freebsd11.0/5.4.0/include-fixed/stdlib.h:192:46: error: expected initializer before '__nonnull'
 int  posix_memalign(void **, size_t, size_t) __nonnull(1); /* (ADV) */
                                              ^
In file included from /usr/local/include/glib-2.0/glib/deprecated/gthread.h:127:0,
                 from /usr/local/include/glib-2.0/glib.h:107,
                 from caps.cc:21:
/usr/local/lib/gcc5/gcc/x86_64-portbld-freebsd11.0/5.4.0/include-fixed/sys/types.h:266:9: error: '__vm_ooffset_t' does not name a type
 typedef __vm_ooffset_t vm_ooffset_t;
         ^
/usr/local/lib/gcc5/gcc/x86_64-portbld-freebsd11.0/5.4.0/include-fixed/sys/types.h:268:9: error: '__vm_pindex_t' does not name a type
 typedef __vm_pindex_t vm_pindex_t;
         ^
gmake[3]: *** [Makefile:1650: libvte_2_91_la-caps.lo] Error 1
gmake[3]: Leaving directory '/usr/home/gregf/vte-ng/src'
gmake[2]: *** [Makefile:1200: all] Error 2
gmake[2]: Leaving directory '/usr/home/gregf/vte-ng/src'
gmake[1]: *** [Makefile:570: all-recursive] Error 1
gmake[1]: Leaving directory '/usr/home/gregf/vte-ng'
gmake: *** [Makefile:477: all] Error 2
```

**Comment by jelly** [comment]
Hmm I don't run FreeBSD 11, I do know it's fairly different. I suggest you look into the vte3 port? And check if there are any FreeBSD specific patches.

**Comment by thestinger** [comment]
You'll need to do whatever is done for vte3.
